name: "Optimize Images"
description: "Optimize images for web"
author: "Matt Struble"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
