name: Python
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths: ["**.py"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: "1.6.1"

      - name: Install Dependencies
        shell: bash
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root --all-extras

      - name: Run Pytest
        shell: bash
        run: |
          pytest . -n auto --timeout=30 --cov

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
