name: Semantic Release

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: release
        id: release
        uses: python-semantic-release/python-semantic-release@v8.0.8
        with:
          github_token: ${{ secrets.CI_GITHUB_TOKEN }}
          git_committer_name: "semantic-release-bot"
          git_committer_email: "semantic-release-bot@martynus.net"
